/*
 * generated by Xtext 2.9.0
 */
package net.aokv.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import net.aokv.datenmodell.Datenmodell

@RunWith(XtextRunner)
@InjectWith(DatenmodellInjectorProvider)
class DatenmodellParsingTest{

	@Inject
	ParseHelper<Datenmodell> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNull(result)
	}

}
