/*
 * generated by Xtext 2.9.0
 */
package net.aokv


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DatenmodellStandaloneSetup extends DatenmodellStandaloneSetupGenerated {

	def static void doSetup() {
		new DatenmodellStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
