/*
 * generated by Xtext 2.9.0
 */
package net.aokv

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DatenmodellRuntimeModule extends AbstractDatenmodellRuntimeModule {
	
}
