/*
 * generated by Xtext
 */
package net.aokv.ui.tests;

import com.google.inject.Injector;
import net.aokv.datenmodell.ui.internal.DatenmodellActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DatenmodellUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DatenmodellActivator.getInstance().getInjector("net.aokv.Datenmodell");
	}

}
